name: AxiumMenu
version: '${version}'
main: me.artaphy.axiumMenu.AxiumMenu
api-version: '1.13'
softdepend: [PlaceholderAPI]
authors: [Artaphy]
description: A powerful and flexible menu plugin for Minecraft servers
website: https://github.com/artaphy/axiummenu

commands:
  axiummenu:
    description: Main command for AxiumMenu
    usage: /<command> [open|reload|list|serve]
    aliases: [am, menu]
    permission: axiummenu.command
